version: "1.0"
services:

  node_red_vue:
    build: .

    networks:
      - node_red_vue

    ports:
      - "1880:1880"
      - "3000:3000"

    environment:
      DB_USER: root
      DB_PASS: pass
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: demo

      AZURE_CLIENTID: ${AZURE_CLIENTID}
      AZURE_TENANTID: ${AZURE_TENANTID}
      AZURE_CLIENTSECRET: ${AZURE_CLIENTSECRET}

      SBSIP_URL: ${SBSIP_URL}
      SBSYS_URL: ${SBSYS_URL}
      SBSIP_USER: ${SBSIP_USER}
      SBSIP_PASS: ${SBSIP_PASS}
      SBSIP_CLIENT: ${SBSIP_CLIENT}
      SBSIP_SECRET: ${SBSIP_SECRET}
      SBSIP_GRANTTYPE: ${SBSIP_GRANTTYPE}

      CREDENTIAL_SECRET: ${CREDENTIAL_SECRET}

      DEV_ENV: "true"
      
      MAIL_THIS: "attester@randers.dk"
      MAIL_USER: ${MAIL_PASS}
      MAIL_PASS: ${MAIL_PASS}
      MAIL_IMAP_URL: ${MAIL_IMAP_URL}
      MAIL_SMTP_URL: ${MAIL_SMTP_URL}

      MAIL_HOVEDPOST: "randers.kommune@randers.dk"
      MAIL_SIGNFLOW: "signflow@randers.dk"
      MAIL_HR: "personalehr@randers.dk"

      SFTP_URL: "sftp.randers.dk"
      SFTP_USER: ${SFTP_USER}
      SFTP_PASS: ${SFTP_PASS}

      SD_USER: ${SD_USER}
      SD_PASS: ${SD_PASS}
            
      # Miljøvariablen FLOWS fortæller Node-RED IDEet hvilket flow.json den skal åbne og gemme ændringer i ved deploy.
      FLOWS: "/data/flows.json"

      # Express miljøvariabler
      VUE_PORT: 3000
      BACKEND_URL: http://localhost:1880
      
      # Bind mount fra codespace til den kørende containers /data.
      # Gør det muligt at deploye flowkode direkte fra IDE og bruge git til at comitte ændringerne til repo.
    volumes:
      - "./node-red/:/data" 
      
    depends_on: 
      db:
        condition: service_healthy
  db:
    image: mariadb:10.6.11
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: pass
      MARIADB_DATABASE: demo
    command: [
        '--wait_timeout=90',
        '--connect_timeout=60',
        '--max_connections=1000'
    ]
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u root --password=pass
      start_period: 5s
      interval: 5s
      timeout: 5s
      retries: 55
    networks:
      - node_red_vue
      
networks: 
  node_red_vue:
    name: node_red_vue
